<center><img src='../assets/images/aau_logo.png' width='10%'></center>

<br>
<center><h3>Addis Ababa University
<br>College of Natural and Computational Sciences
<br>Department of Computer Science</h3></center>

---
<center><h1 style="font-weight: bold;">CoSc 6262: Data Science</h1></center>
<center><img src='../assets/images/numpy_logo.png' width='25%'></center>
<br>
<center><h2>Assignment 1: NumPy</h2> </center>

---

## Questions

### Question 1

Create a random vector of size 20 and sort it (Descending).

In [1]:
import numpy as np

vec = np.random.random(20)
sorted_vec = np.sort(vec)[::-1]
print("\nSorted vector (descending):")
print(sorted_vec)


Sorted vector (descending):
[0.99532575 0.95972913 0.93084855 0.81890027 0.74888697 0.73490477
 0.70480705 0.68074521 0.67999525 0.62133217 0.61994666 0.50958308
 0.48808705 0.47454352 0.43487118 0.31633344 0.22736476 0.20851152
 0.16701448 0.00740801]


### Question 2

Create a 5*5 array with 6 on the border and 0 inside.

> Hint: output is expected to be:  
  
>  [[ 6.  6.  6.  6.  6.]  
>   [ 6.  0.  0.  0.  6.]  
>   [ 6.  0.  0.  0.  6.]  
>   [ 6.  0.  0.  0.  6.]  
>   [ 6.  6.  6.  6.  6.]])  

In [2]:
array_5x5 = np.full((5, 5), 6)
array_5x5[1:-1, 1:-1] = 0
print("\n5x5 array with border 6 and inner 0:")
print(array_5x5)


5x5 array with border 6 and inner 0:
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


### Question 3

Create a random 10*10 Matrix. Calculate the minimum, maximum, average value for each row and columns. 

In [3]:
matrix = np.random.random((10, 10))

row_min = np.min(matrix, axis=1)
row_max = np.max(matrix, axis=1)
row_avg = np.mean(matrix, axis=1)

col_min = np.min(matrix, axis=0)
col_max = np.max(matrix, axis=0)
col_avg = np.mean(matrix, axis=0)

print("\n10x10 Matrix:")
print(matrix)


10x10 Matrix:
[[0.9983414  0.66162381 0.73922704 0.56773222 0.1513276  0.97439119
  0.15739481 0.98938956 0.71313139 0.30288687]
 [0.11947303 0.66884755 0.3969114  0.55839437 0.1388236  0.25382975
  0.17343571 0.33422074 0.99215925 0.10020197]
 [0.94872366 0.55405647 0.20878918 0.10147047 0.20307062 0.69454326
  0.16007958 0.81278536 0.24054573 0.66476635]
 [0.89562815 0.94301174 0.30626658 0.71842359 0.56886379 0.70992791
  0.85007893 0.69947437 0.74529373 0.75104342]
 [0.39661023 0.2947805  0.70955618 0.98860725 0.93248613 0.40367423
  0.71046293 0.5655053  0.76549998 0.07409354]
 [0.8402827  0.10043739 0.22269018 0.46962174 0.41867083 0.37315251
  0.77801649 0.98887784 0.70472467 0.20651079]
 [0.32266529 0.86460037 0.32157894 0.38038037 0.77939885 0.31749337
  0.93400586 0.61916229 0.44347855 0.75798587]
 [0.77138905 0.83040169 0.20671573 0.42850698 0.84798211 0.42036539
  0.02210324 0.21265284 0.03240452 0.91000911]
 [0.16067173 0.37349423 0.39363915 0.86036411 0.98856095 0.278437

In [4]:
print("\nRow statistics:")
print("Min:", row_min)
print("Max:", row_max)
print("Average:", row_avg)


Row statistics:
Min: [0.1513276  0.10020197 0.10147047 0.30626658 0.07409354 0.10043739
 0.31749337 0.02210324 0.07402628 0.09379523]
Max: [0.9983414  0.99215925 0.94872366 0.94301174 0.98860725 0.98887784
 0.93400586 0.91000911 0.98856095 0.95719895]
Average: [0.62554459 0.37362974 0.45888307 0.71880122 0.58412763 0.51029851
 0.57407498 0.46825307 0.54192752 0.55911683]


In [5]:
print("\nColumn statistics:")
print("Min:", col_min)
print("Max:", col_max)
print("Average:", col_avg)


Column statistics:
Min: [0.11947303 0.10043739 0.20671573 0.09379523 0.1388236  0.25382975
 0.02210324 0.07402628 0.03240452 0.07409354]
Max: [0.9983414  0.94301174 0.79900372 0.98860725 0.98856095 0.97439119
 0.93400586 0.98938956 0.99215925 0.91000911]
Average: [0.64109842 0.59912827 0.43043781 0.51672963 0.538165   0.53730208
 0.54847202 0.54476441 0.58510945 0.47345007]


### Question 4

Generate a random 8 elements vector, then build a new vector with 2 consecutive zeros interleaved between each value. 

> [Hint: answer is expected as: [1,0,0,3,0,0,5]]

In [6]:
vec8 = np.random.randint(0, 10, size=8)

# Create new list with 2 zeros between each original value
interleaved = []
for i, num in enumerate(vec8):
    interleaved.append(num)
    if i != len(vec8) - 1:
        interleaved.extend([0, 0])
interleaved = np.array(interleaved)
print("\nOriginal vector (8 elements):")
print(vec8)
print("\nModified vector with interleaved zeros:")
print(interleaved)


Original vector (8 elements):
[8 9 4 2 8 4 7 1]

Modified vector with interleaved zeros:
[8 0 0 9 0 0 4 0 0 2 0 0 8 0 0 4 0 0 7 0 0 1]


### Question 5

Generate a random 4 by 4 array and swap first 2 rows.

In [7]:
array_4x4 = np.random.random((4,4))
swapped_array = array_4x4.copy()
swapped_array[[0, 1]] = swapped_array[[1, 0]]
print("\nOriginal 4x4 array:")
print(array_4x4)
print("\nArray after swapping first two rows:")
print(swapped_array)


Original 4x4 array:
[[0.62648695 0.58943875 0.06965573 0.74291811]
 [0.76384876 0.37471073 0.68028562 0.61138205]
 [0.50276751 0.82722505 0.55340976 0.84275761]
 [0.53365456 0.61236391 0.90151753 0.73495508]]

Array after swapping first two rows:
[[0.76384876 0.37471073 0.68028562 0.61138205]
 [0.62648695 0.58943875 0.06965573 0.74291811]
 [0.50276751 0.82722505 0.55340976 0.84275761]
 [0.53365456 0.61236391 0.90151753 0.73495508]]


### Question 6

Considering a 20x2 matrix, extract the rows with unequal values. 

> (e.g. if A=[[1 2][3 3][5 6]], then the output is expected to be [[1 2][5 6]])

In [8]:
matrix_20x2 = np.random.randint(0, 10, size=(20, 2))
unequal_rows = matrix_20x2[matrix_20x2[:, 0] != matrix_20x2[:, 1]]
print("\n20x2 Matrix:")
print(matrix_20x2)
print("\nRows with unequal values:")
print(unequal_rows)


20x2 Matrix:
[[5 4]
 [4 7]
 [7 5]
 [3 3]
 [3 3]
 [4 1]
 [5 9]
 [1 4]
 [8 3]
 [6 7]
 [5 3]
 [6 2]
 [4 1]
 [0 2]
 [6 8]
 [7 9]
 [2 9]
 [4 5]
 [1 6]
 [2 8]]

Rows with unequal values:
[[5 4]
 [4 7]
 [7 5]
 [4 1]
 [5 9]
 [1 4]
 [8 3]
 [6 7]
 [5 3]
 [6 2]
 [4 1]
 [0 2]
 [6 8]
 [7 9]
 [2 9]
 [4 5]
 [1 6]
 [2 8]]


### Question 7

Generate an array from 1 to 50, then build and apply the function, which filters out all prime numbers in the array.

In [9]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

arr_1_to_50 = np.arange(1, 51)

# Filter out prime numbers
non_primes = [x for x in arr_1_to_50 if not is_prime(x)]
print("\nArray from 1 to 50:")
print(arr_1_to_50)
print("\nAfter filtering out prime numbers:")
print([int(x) for x in non_primes])


Array from 1 to 50:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

After filtering out prime numbers:
[1, 4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 25, 26, 27, 28, 30, 32, 33, 34, 35, 36, 38, 39, 40, 42, 44, 45, 46, 48, 49, 50]


## Additional Cells

### Broadcasting

Using broadcasting to add a vector to each row of a matrix

In [10]:
A = np.random.randint(1, 10, (5, 3))
b = np.array([10, 20, 30])
result = A + b
print("\nMatrix A:")
print(A)
print("\nVector b:")
print(b)
print("\nResult:")
print(result)


Matrix A:
[[4 2 2]
 [3 1 6]
 [7 5 5]
 [7 6 7]
 [6 6 6]]

Vector b:
[10 20 30]

Result:
[[14 22 32]
 [13 21 36]
 [17 25 35]
 [17 26 37]
 [16 26 36]]


### Boolean indexing

Boolean indexing to filter even numbers from a matrix

In [11]:
matrix_bonus = np.random.randint(1, 50, (4, 4))
even_mask = matrix_bonus % 2 == 0
even_numbers = matrix_bonus[even_mask]
print("\nOriginal matrix:")
print(matrix_bonus)
print("\nEven numbers extracted:")
print(even_numbers)


Original matrix:
[[27 21  9 34]
 [43  4 45 21]
 [27 27 41 45]
 [16 12 29  7]]

Even numbers extracted:
[34  4 16 12]


### Reshape & tile

Reshape and tile an array

In [12]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
tiled = np.tile(reshaped, (2, 3))  # repeats 2 times vertically and 3 times horizontally
print("\nOriginal array:")
print(arr)
print("\nReshaped (3x4):")
print(reshaped)
print("\nTiled array (2,3 times):")
print(tiled)


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Tiled array (2,3 times):
[[ 0  1  2  3  0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11  8  9 10 11]
 [ 0  1  2  3  0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11  8  9 10 11]]


### Universal functions

Applying universal functions (sin and cos)

In [13]:
angles = np.linspace(0, 2 * np.pi, 5)
sin_values = np.sin(angles)
cos_values = np.cos(angles)
print("\nAngles:")
print(angles)
print("\nSin values:")
print(sin_values)


Angles:
[0.         1.57079633 3.14159265 4.71238898 6.28318531]

Sin values:
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
